<template>
    <div>
        <!-- <el-table :data='result' border stripe slot='table' row-key='id'>
            <el-table-column prop='str' label='风险分类及风险点' header-align="center"></el-table-column>
            <el-table-column prop='value' label='阈值' align="center" width='400'>
                <template slot-scope="{row}">
                    <div v-if="row.value!=undefined">
                        <el-input v-model="row.value" style="width:60%;margin-right:20px;" size="mini" @blur="changeInput(row)" /> 万元
                    </div>
                    <div v-else></div>
                </template>
            </el-table-column>
        </el-table>-->
        <!-- <el-table :data='result' border stripe slot='table' row-key='id'>
            <el-table-column prop='str' label='风险分类及风险点' header-align="center"></el-table-column>
            <el-table-column prop='value' label='阈值' align="center" width='400'>
                <template slot-scope="{row}">
                    <div v-if="row.value!=undefined">
                        <el-input v-model="row.value" style="width:60%;margin-right:20px;" size="mini" @blur="changeInput(row)" /> 万元
                    </div>
                    <div v-else></div>
                </template>
            </el-table-column>
        </el-table>-->
        <!-- <enlarge-the-picture></enlarge-the-picture> -->
        <bubble></bubble>
        <data></data>
    </div>
</template>

<script>
import EnlargeThePicture from './enlargeImg' //图片放大缩小
import Bubble from './bubble' //小气泡
import Data from './data' //时间过虑
export default {
    name: 'HelloWorld',
    data() {
        return {
            obj: {},
            result: [
                { id: 1, projectId: 'Pj4419000005', c1: '01', c1str: '品质', isSubShow: false },
                {
                    id: 2,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    icon: 'icon-huanjingpinzhi3',
                    isSubShow: false
                },
                {
                    id: 3,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010101',
                    c3str: '热湿环境',
                    isSubShow: false
                },
                {
                    id: 4,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010101',
                    c3str: '热湿环境',
                    c4: '01010101',
                    c4str: '室内温度过高',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 5,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010101',
                    c3str: '热湿环境',
                    c4: '01010102',
                    c4str: '室内环境偏冷',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 6,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010101',
                    c3str: '热湿环境',
                    c4: '01010103',
                    c4str: '室内温度不均',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 7,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010101',
                    c3str: '热湿环境',
                    c4: '01010104',
                    c4str: '室内湿度偏大',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 8,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010101',
                    c3str: '热湿环境',
                    c4: '01010105',
                    c4str: '室内干燥',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 9,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010102',
                    c3str: '空气品质',
                    isSubShow: false
                },
                {
                    id: 10,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010102',
                    c3str: '空气品质',
                    c4: '01010201',
                    c4str: '甲醛超标',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 11,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010102',
                    c3str: '空气品质',
                    c4: '01010202',
                    c4str: 'CO2超标',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 12,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010102',
                    c3str: '空气品质',
                    c4: '01010203',
                    c4str: 'VOC超标',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 13,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010102',
                    c3str: '空气品质',
                    c4: '01010204',
                    c4str: 'PM2.5超标',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 14,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010103',
                    c3str: '声环境',
                    isSubShow: false
                },
                {
                    id: 15,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010103',
                    c3str: '声环境',
                    c4: '01010301',
                    c4str: '噪音超标',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 16,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010103',
                    c3str: '声环境',
                    c4: '01010302',
                    c4str: '背景音乐缺失',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 17,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010104',
                    c3str: '光环境',
                    isSubShow: false
                },
                {
                    id: 18,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010104',
                    c3str: '光环境',
                    c4: '01010401',
                    c4str: '基础照明中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 19,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010104',
                    c3str: '光环境',
                    c4: '01010402',
                    c4str: '照度不足',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 20,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010104',
                    c3str: '光环境',
                    c4: '01010403',
                    c4str: '装饰照明中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 21,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010104',
                    c3str: '光环境',
                    c4: '01010404',
                    c4str: '照明过度',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 22,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010104',
                    c3str: '光环境',
                    c4: '01010405',
                    c4str: '炫光',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 23,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010105',
                    c3str: '室内装修损坏',
                    isSubShow: false
                },
                {
                    id: 24,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010105',
                    c3str: '室内装修损坏',
                    c4: '01010501',
                    c4str: '地砖问题',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 25,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010105',
                    c3str: '室内装修损坏',
                    c4: '01010502',
                    c4str: '墙皮问题',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 26,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010105',
                    c3str: '室内装修损坏',
                    c4: '01010503',
                    c4str: '吊顶问题',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 27,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0101',
                    c2str: '环境品质风险',
                    c3: '010105',
                    c3str: '室内装修损坏',
                    c4: '01010504',
                    c4str: '广告灯箱问题',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 28,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0102',
                    c2str: '基础服务局部中断风险',
                    icon: 'icon-jichufuwuzhongduan3',
                    isSubShow: false
                },
                {
                    id: 29,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0102',
                    c2str: '基础服务局部中断风险',
                    c3: '010201',
                    c3str: '电梯系统故障',
                    isSubShow: false
                },
                {
                    id: 30,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0102',
                    c2str: '基础服务局部中断风险',
                    c3: '010201',
                    c3str: '电梯系统故障',
                    c4: '01020101',
                    c4str: '电梯失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 31,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0102',
                    c2str: '基础服务局部中断风险',
                    c3: '010201',
                    c3str: '电梯系统故障',
                    c4: '01020102',
                    c4str: '电梯门关不上',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 32,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0102',
                    c2str: '基础服务局部中断风险',
                    c3: '010201',
                    c3str: '电梯系统故障',
                    c4: '01020103',
                    c4str: '电梯异响',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 33,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    icon: 'icon-sheshiguzhang3',
                    isSubShow: false
                },
                {
                    id: 34,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010301',
                    c3str: '盥洗间问题',
                    isSubShow: false
                },
                {
                    id: 35,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010301',
                    c3str: '盥洗间问题',
                    c4: '01030101',
                    c4str: '马桶堵塞',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 36,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010301',
                    c3str: '盥洗间问题',
                    c4: '01030102',
                    c4str: '马桶故障',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 37,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010301',
                    c3str: '盥洗间问题',
                    c4: '01030103',
                    c4str: '洗手池故障',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 38,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010301',
                    c3str: '盥洗间问题',
                    c4: '01030104',
                    c4str: '洗手间排风机故障',
                    isSubShow: false
                },
                {
                    id: 39,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010301',
                    c3str: '盥洗间问题',
                    c4: '01030105',
                    c4str: '卫生间停水',
                    isSubShow: false
                },
                {
                    id: 40,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010302',
                    c3str: '污水系统溢水',
                    isSubShow: false
                },
                {
                    id: 41,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010302',
                    c3str: '污水系统溢水',
                    c4: '01030201',
                    c4str: '污水坑溢水',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 42,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010303',
                    c3str: '停车场系统',
                    isSubShow: false
                },
                {
                    id: 43,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010303',
                    c3str: '停车场系统',
                    c4: '01030301',
                    c4str: '收费机器故障',
                    isSubShow: false
                },
                {
                    id: 44,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010303',
                    c3str: '停车场系统',
                    c4: '01030302',
                    c4str: '道闸故障',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 45,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010303',
                    c3str: '停车场系统',
                    c4: '01030303',
                    c4str: '引导指示灯故障',
                    isSubShow: false
                },
                {
                    id: 46,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010304',
                    c3str: '购物引导问题',
                    isSubShow: false
                },
                {
                    id: 47,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010304',
                    c3str: '购物引导问题',
                    c4: '01030401',
                    c4str: '室内指示牌故障',
                    isSubShow: false
                },
                {
                    id: 48,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010304',
                    c3str: '购物引导问题',
                    c4: '01030402',
                    c4str: '广播系统故障',
                    isSubShow: false
                },
                {
                    id: 49,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010304',
                    c3str: '购物引导问题',
                    c4: '01030403',
                    c4str: '购物导引设备故障',
                    isSubShow: false
                },
                {
                    id: 50,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010305',
                    c3str: '室外展示问题',
                    isSubShow: false
                },
                {
                    id: 51,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010305',
                    c3str: '室外展示问题',
                    c4: '01030501',
                    c4str: '广告牌故障、脱落',
                    isSubShow: false
                },
                {
                    id: 52,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010305',
                    c3str: '室外展示问题',
                    c4: '01030502',
                    c4str: '引导指示损坏',
                    isSubShow: false
                },
                {
                    id: 53,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010306',
                    c3str: '垃圾房问题',
                    isSubShow: false
                },
                {
                    id: 54,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010306',
                    c3str: '垃圾房问题',
                    c4: '01030601',
                    c4str: '垃圾房风机故障',
                    isSubShow: false
                },
                {
                    id: 55,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010307',
                    c3str: '厨房问题',
                    isSubShow: false
                },
                {
                    id: 56,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010307',
                    c3str: '厨房问题',
                    c4: '01030701',
                    c4str: '厨房排风机故障',
                    isSubShow: false
                },
                {
                    id: 57,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010307',
                    c3str: '厨房问题',
                    c4: '01030702',
                    c4str: '厨房排烟不畅',
                    isSubShow: false
                },
                {
                    id: 58,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010308',
                    c3str: '水景问题',
                    isSubShow: false
                },
                {
                    id: 59,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010308',
                    c3str: '水景问题',
                    c4: '01030801',
                    c4str: '水景水泵故障',
                    isSubShow: false
                },
                {
                    id: 60,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010308',
                    c3str: '水景问题',
                    c4: '01030802',
                    c4str: '水景缺水',
                    isSubShow: false
                },
                {
                    id: 61,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010308',
                    c3str: '水景问题',
                    c4: '01030803',
                    c4str: '水景喷头异常',
                    isSubShow: false
                },
                {
                    id: 62,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010309',
                    c3str: '空调问题',
                    isSubShow: false
                },
                {
                    id: 63,
                    projectId: 'Pj4419000005',
                    c1: '01',
                    c1str: '品质',
                    c2: '0103',
                    c2str: '设施故障或缺失风险',
                    c3: '010309',
                    c3str: '空调问题',
                    c4: '01030901',
                    c4str: '空调积水盘滴水',
                    isSubShow: false
                },
                { id: 64, projectId: 'Pj4419000005', c1: '02', c1str: '成本', isSubShow: false },
                { id: 65, projectId: 'Pj4419000005', c1: '02', c1str: '成本', c2: '0201', c2str: '高能耗风险', isSubShow: false },
                {
                    id: 66,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0201',
                    c2str: '高能耗风险',
                    c3: '020101',
                    c3str: '能耗超预算',
                    isSubShow: false
                },
                {
                    id: 67,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0201',
                    c2str: '高能耗风险',
                    c3: '020101',
                    c3str: '能耗超预算',
                    c4: '02010101',
                    c4str: '能耗成本超预算',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 68,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0201',
                    c2str: '高能耗风险',
                    c3: '020102',
                    c3str: '能耗成本不合理增加',
                    isSubShow: false
                },
                {
                    id: 69,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0201',
                    c2str: '高能耗风险',
                    c3: '020102',
                    c3str: '能耗成本不合理增加',
                    c4: '02010201',
                    c4str: '能耗异常',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 70,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0201',
                    c2str: '高能耗风险',
                    c3: '020102',
                    c3str: '能耗成本不合理增加',
                    c4: '02010202',
                    c4str: '运行成本过高',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                { id: 71, projectId: 'Pj4419000005', c1: '02', c1str: '成本', c2: '0202', c2str: '运维成本超限风险', isSubShow: false },
                {
                    id: 72,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020201',
                    c3str: '维修成本过高',
                    isSubShow: false
                },
                {
                    id: 73,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020201',
                    c3str: '维修成本过高',
                    c4: '02020101',
                    c4str: '备品备件消耗快',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 74,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020201',
                    c3str: '维修成本过高',
                    c4: '02020102',
                    c4str: '维修持续时间长',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 75,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020201',
                    c3str: '维修成本过高',
                    c4: '02020103',
                    c4str: '采购价高于市场价',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 76,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020202',
                    c3str: '维保成本过高',
                    isSubShow: false
                },
                {
                    id: 77,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020202',
                    c3str: '维保成本过高',
                    c4: '02020201',
                    c4str: '外委价格高于市场价',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 78,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020202',
                    c3str: '维保成本过高',
                    c4: '02020202',
                    c4str: '小维保不做导致设备出现大的问题',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 79,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020203',
                    c3str: '巡检成本过高',
                    isSubShow: false
                },
                {
                    id: 80,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020203',
                    c3str: '巡检成本过高',
                    c4: '02020301',
                    c4str: '巡检持续时间长',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 81,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0202',
                    c2str: '运维成本超限风险',
                    c3: '020203',
                    c3str: '巡检成本过高',
                    c4: '02020302',
                    c4str: '巡检频次过高',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                { id: 82, projectId: 'Pj4419000005', c1: '02', c1str: '成本', c2: '0203', c2str: '设备寿命缩短风险', isSubShow: false },
                {
                    id: 83,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0203',
                    c2str: '设备寿命缩短风险',
                    c3: '020301',
                    c3str: '设备寿命缩短',
                    isSubShow: false
                },
                {
                    id: 84,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0203',
                    c2str: '设备寿命缩短风险',
                    c3: '020301',
                    c3str: '设备寿命缩短',
                    c4: '02030101',
                    c4str: '维保不到位',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 85,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0203',
                    c2str: '设备寿命缩短风险',
                    c3: '020301',
                    c3str: '设备寿命缩短',
                    c4: '02030102',
                    c4str: '使用环境恶劣',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 86,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0203',
                    c2str: '设备寿命缩短风险',
                    c3: '020301',
                    c3str: '设备寿命缩短',
                    c4: '02030103',
                    c4str: '超负荷使用',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 87,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0203',
                    c2str: '设备寿命缩短风险',
                    c3: '020301',
                    c3str: '设备寿命缩短',
                    c4: '02030104',
                    c4str: '附件损坏导致设备寿命缩短',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                { id: 88, projectId: 'Pj4419000005', c1: '02', c1str: '成本', c2: '0204', c2str: '服务费用计量失准风险', isSubShow: false },
                {
                    id: 89,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020401',
                    c3str: '偷漏电风险',
                    isSubShow: false
                },
                {
                    id: 90,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020401',
                    c3str: '偷漏电风险',
                    c4: '02040101',
                    c4str: '偷电风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 91,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020402',
                    c3str: '偷漏水风险',
                    isSubShow: false
                },
                {
                    id: 92,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020402',
                    c3str: '偷漏水风险',
                    c4: '02040201',
                    c4str: '自来水偷水风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 93,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020402',
                    c3str: '偷漏水风险',
                    c4: '02040202',
                    c4str: '生活热水偷水风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 94,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020403',
                    c3str: '用能计量错误风险',
                    isSubShow: false
                },
                {
                    id: 95,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020403',
                    c3str: '用能计量错误风险',
                    c4: '02040301',
                    c4str: '用电量计量错误',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 96,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020403',
                    c3str: '用能计量错误风险',
                    c4: '02040302',
                    c4str: '用水量计量错误',
                    upperLimit: 5.0,
                    value: 0.0,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 97,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0204',
                    c2str: '服务费用计量失准风险',
                    c3: '020403',
                    c3str: '用能计量错误风险',
                    c4: '02040303',
                    c4str: '热水两计量错误',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                { id: 98, projectId: 'Pj4419000005', c1: '02', c1str: '成本', c2: '0205', c2str: '资产闲置风险', isSubShow: false },
                {
                    id: 99,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0205',
                    c2str: '资产闲置风险',
                    c3: '020501',
                    c3str: '资产闲置',
                    isSubShow: false
                },
                {
                    id: 100,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0205',
                    c2str: '资产闲置风险',
                    c3: '020501',
                    c3str: '资产闲置',
                    c4: '02050101',
                    c4str: '设计冗余偏大导致大量资产闲置',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 101,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0205',
                    c2str: '资产闲置风险',
                    c3: '020501',
                    c3str: '资产闲置',
                    c4: '02050102',
                    c4str: '空间功能设计与实际不符',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 102,
                    projectId: 'Pj4419000005',
                    c1: '02',
                    c1str: '成本',
                    c2: '0205',
                    c2str: '资产闲置风险',
                    c3: '020501',
                    c3str: '资产闲置',
                    c4: '02050103',
                    c4str: '空间功能变更导致闲置',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                { id: 103, projectId: 'Pj4419000005', c1: '03', c1str: '事故', isSubShow: false },
                {
                    id: 104,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    icon: 'icon-xiaofang3',
                    isSubShow: false
                },
                {
                    id: 105,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    isSubShow: false
                },
                {
                    id: 106,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010101',
                    c4str: '电力起火',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 107,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010102',
                    c4str: '设备起火-强电专业',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 108,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010103',
                    c4str: '设备起火-弱电专业',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 109,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010104',
                    c4str: '设备起火-空调专业',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 110,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010105',
                    c4str: '设备起火-给排水专业',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 111,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010106',
                    c4str: '设备起火-消防专业',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 112,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010107',
                    c4str: '设备起火-安防专业',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 113,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010108',
                    c4str: '其他起火',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 114,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010109',
                    c4str: '燃气起火',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 115,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030101',
                    c3str: '起火风险',
                    c4: '03010110',
                    c4str: '空间起火',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 116,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    isSubShow: false
                },
                {
                    id: 117,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010201',
                    c4str: '逃生通道失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 118,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010202',
                    c4str: '灭火设施失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 119,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010203',
                    c4str: '逃生设施失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 120,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010204',
                    c4str: '应急照明失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 121,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010205',
                    c4str: '消防报警设施失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 122,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010206',
                    c4str: '燃气报警设施失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 123,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0301',
                    c2str: '消防风险',
                    c3: '030102',
                    c3str: '火灾蔓延风险',
                    c4: '03010207',
                    c4str: '消防联动失效',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 124,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    icon: 'icon-zhengcehegui3',
                    isSubShow: false
                },
                {
                    id: 125,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030201',
                    c3str: '消防政策合规',
                    isSubShow: false
                },
                {
                    id: 126,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030201',
                    c3str: '消防政策合规',
                    c4: '03020101',
                    c4str: '消防维护记录不全',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 127,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030201',
                    c3str: '消防政策合规',
                    c4: '03020102',
                    c4str: '消防设备状态异常',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 128,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030201',
                    c3str: '消防政策合规',
                    c4: '03020103',
                    c4str: '消防作业人员不合规',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 129,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030202',
                    c3str: '废气排放合规',
                    isSubShow: false
                },
                {
                    id: 130,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030202',
                    c3str: '废气排放合规',
                    c4: '03020201',
                    c4str: '废气维护记录不全',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 131,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030202',
                    c3str: '废气排放合规',
                    c4: '03020202',
                    c4str: '废气设备状态异常',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 132,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030203',
                    c3str: '废水排放合规',
                    isSubShow: false
                },
                {
                    id: 133,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030203',
                    c3str: '废水排放合规',
                    c4: '03020301',
                    c4str: '废水维护记录不全',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 134,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030203',
                    c3str: '废水排放合规',
                    c4: '03020302',
                    c4str: '废水设备状态异常',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 135,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030204',
                    c3str: '室内空气合规',
                    isSubShow: false
                },
                {
                    id: 136,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030204',
                    c3str: '室内空气合规',
                    c4: '03020401',
                    c4str: '空气品质维护记录不全',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 137,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030204',
                    c3str: '室内空气合规',
                    c4: '03020402',
                    c4str: '空气品质设备状态异常',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 138,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030205',
                    c3str: '作业人员合规',
                    isSubShow: false
                },
                {
                    id: 139,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030205',
                    c3str: '作业人员合规',
                    c4: '03020501',
                    c4str: '电力作业人员不合规',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 140,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0302',
                    c2str: '政策合规',
                    c3: '030205',
                    c3str: '作业人员合规',
                    c4: '03020502',
                    c4str: '电梯作业人员不合规',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 141,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    icon: 'icon-renshenshanghai3',
                    isSubShow: false
                },
                {
                    id: 142,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030301',
                    c3str: '困人',
                    isSubShow: false
                },
                {
                    id: 143,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030301',
                    c3str: '困人',
                    c4: '03030101',
                    c4str: '电梯困人',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 144,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030301',
                    c3str: '困人',
                    c4: '03030102',
                    c4str: '空间困人',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 145,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030301',
                    c3str: '困人',
                    c4: '03030103',
                    c4str: '设备困人',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 146,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030302',
                    c3str: '人员坠落',
                    isSubShow: false
                },
                {
                    id: 147,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030302',
                    c3str: '人员坠落',
                    c4: '03030201',
                    c4str: '人员坠落风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 148,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030303',
                    c3str: '高空坠物',
                    isSubShow: false
                },
                {
                    id: 149,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030303',
                    c3str: '高空坠物',
                    c4: '03030301',
                    c4str: '高空物体砸落',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 150,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030303',
                    c3str: '高空坠物',
                    c4: '03030302',
                    c4str: '广告装饰坠落',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 151,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030304',
                    c3str: '触电',
                    isSubShow: false
                },
                {
                    id: 152,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030304',
                    c3str: '触电',
                    c4: '03030401',
                    c4str: '人员触电风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 153,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030305',
                    c3str: '机械伤害',
                    isSubShow: false
                },
                {
                    id: 154,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030305',
                    c3str: '机械伤害',
                    c4: '03030501',
                    c4str: '机械绞伤',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 155,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0303',
                    c2str: '人身伤害',
                    c3: '030305',
                    c3str: '机械伤害',
                    c4: '03030502',
                    c4str: '尖锐划伤',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 156,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    icon: 'icon-zhongdianjichufuwuzhongduan3',
                    isSubShow: false
                },
                {
                    id: 157,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    isSubShow: false
                },
                {
                    id: 158,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040101',
                    c4str: '生活用水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 159,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040102',
                    c4str: '中水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 160,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040103',
                    c4str: '生活热水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 161,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040104',
                    c4str: '直饮水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 162,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040105',
                    c4str: '水景用水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 163,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040106',
                    c4str: '喷灌用水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 164,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030401',
                    c3str: '停水风险',
                    c4: '03040107',
                    c4str: '娱乐用水大面积中断',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 165,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030402',
                    c3str: '停电风险',
                    isSubShow: false
                },
                {
                    id: 166,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030402',
                    c3str: '停电风险',
                    c4: '03040201',
                    c4str: '大面积停电风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 167,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030403',
                    c3str: '断网风险',
                    isSubShow: false
                },
                {
                    id: 168,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030403',
                    c3str: '断网风险',
                    c4: '03040301',
                    c4str: '大面积断网风险',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 169,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030404',
                    c3str: '断冷风险',
                    isSubShow: false
                },
                {
                    id: 170,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030404',
                    c3str: '断冷风险',
                    c4: '03040401',
                    c4str: '大面积停止供冷',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 171,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030405',
                    c3str: '断热风险',
                    isSubShow: false
                },
                {
                    id: 172,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030405',
                    c3str: '断热风险',
                    c4: '03040501',
                    c4str: '大面积停止供热',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                },
                {
                    id: 173,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030406',
                    c3str: '断气风险',
                    isSubShow: false
                },
                {
                    id: 174,
                    projectId: 'Pj4419000005',
                    c1: '03',
                    c1str: '事故',
                    c2: '0304',
                    c2str: '重点基础服务中断',
                    c3: '030406',
                    c3str: '断气风险',
                    c4: '03040601',
                    c4str: '大面积停止供气',
                    upperLimit: 5.0,
                    value: 0.2,
                    overFlag: 0,
                    isSubShow: false
                }
            ]
        }
    },
    components: {
        EnlargeThePicture
    },
    mounted() {
        this.init()
    },
    methods: {
        filterString(i) {
            delete i.str
            delete i.value
            delete i.id
            return i
        },
        toFormat(obj) {
            let arr = Object.values(obj)
            arr.forEach((i, index) => {
                if (i !== null && typeof i === 'object') {
                    arr[index] = {
                        str: i.str,
                        value: i.value,
                        id: String(i.id),
                        children: this.toFormat(this.filterString(i))
                    }
                }
            })
            return arr
        },
        handleData(i, floor) {
            const dataObj = {
                str: i[`c${floor}str`],
                value: i.upperLimit || i.undefined,
                id: i[`c${floor}`]
            }
            for (let j = 0; j < floor; j++) {
                if (this.obj[i.c1]) {
                    if (floor > 1) {
                        if (this.obj[i.c1][i.c2]) {
                            if (floor > 2) {
                                if (this.obj[i.c1][i.c2][i.c3]) {
                                    if (floor > 3) {
                                        this.obj[i.c1][i.c2][i.c3][i.c4] = dataObj
                                    }
                                } else {
                                    this.obj[i.c1][i.c2][i.c3] = floor === 3 ? dataObj : {}
                                }
                            }
                        } else {
                            this.obj[i.c1][i.c2] = floor === 2 ? dataObj : {}
                        }
                    }
                } else {
                    this.obj[i.c1] = floor === 1 ? dataObj : {}
                }
            }
        },
        init() {
            //     this.result = this.result.reduce((prev, next) => {
            //         // console.log(next)
            //         let arr = Object.keys(next)
            //             .filter(item => item.startsWith('c'))
            //             .sort((a, b) => (a < b ? 1 : -1))
            //         // console.log(arr)
            //         let str2 = arr[1]
            //         // console.log(str2)
            //         let strArr = [...next[str2]]
            //         // console.log(strArr)
            //         // console.log(strArr)
            //         strArr = strArr
            //             .map((item, index, arr) => {
            //                 // console.log(item, index, arr)
            //                 if (index % 2 != 1) {
            //                     return arr[index] + arr[index + 1]
            //                 }
            //             })
            //             .filter(item => item)
            //         // console.log(strArr)
            //         let lingshi = prev
            //         // console.log(lingshi)
            //         for (let i = 0; i < strArr.length; i++) {
            //             let index = parseInt(strArr[i]) - 1
            //             // console.log(index)
            //             if (i == strArr.length - 1) {
            //                 //   lingshi.push({...next, children:[]})
            //                 lingshi[index] = { ...next, children: [] }
            //                 // console.log({...next})
            //                 break
            //             }
            //             lingshi = lingshi[index].children
            //             console.log(lingshi)
            //         }
            //         return prev
            //     }, [])
            this.obj = {}
            this.result.forEach(i => {
                if (i.c4) {
                    // 则c4,c3,c2,c1都存在
                    this.handleData(i, 4)
                } else if (i.c3) {
                    this.handleData(i, 3)
                } else if (i.c2) {
                    this.handleData(i, 2)
                } else if (i.c1) {
                    this.handleData(i, 1)
                }
            })
            this.result = this.toFormat(this.obj)
        }
    }
}
</script>