export const GET_RESTAURANT = 'get_restaurant';  //获取餐厅
export const GET_DISHESBIGCLASS = 'dishesbigclass';  //获取菜品大类
export const GET_DISHESSMALLCLASS = 'dishessmallclass';  //获取菜品小类
export const GET_MEALPERIOD = 'mealperiod';  //获取餐段
export const GET_BILLINGSTATEMENTS = 'billingstatements';  //销售明细数据表
export const GET_SALESSUMMARYTABLE = 'SalesSummaryTable';  //获取餐饮账单明细报表
export const GET_HOTEL = 'hotel';  //获取餐饮账单明细报表
export const GET_OPENCHECKREPORT = 'get_opencheckreport';  //查询结账方式交易明细
export const GET_CLOSEDCHECKSEMPLOYEELIST = 'get_closedchecksemployeelist';  //查询结账方式交易明细
export const GET_ONLINEPAYMENTSUMMARY = 'get_onlinepaymentsummary';  //查询结账方式交易明细
export const GET_SUMMARYTOTAL = 'get_summarytotal';  //查询结账方式交易明细
export const GET_EMPCLOSEDCHECKS = 'get_empclosedchecks';  //查询结账方式交易明细
export const GET_DISCOUNTSUMMMARY = 'get_discountsummmary';  //折扣摘要
export const GET_ENT = 'get_ent';  //宴请
export const GET_REVENUECENTERFINANCIAL = 'get_revenuecenterfinancial';  //餐厅财务报表
export const GET_EMPLOYEESL = 'get_employeesl';  //员工编号
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE'; //token验证
export const FINISH_LOGIN = 'FINISH_LOGIN'; //koken验证
export const GET_BIGCLASSQUERY = 'get_bigclassquery'; //菜品大类
export const GET_FOODCATEGORY = 'get_foodcategory'; //菜品类别
export const GET_FOODBELONGSTOTYPE = 'get_foodbelongstotype';
export const GET_EMPLOYEESREPORT = 'get_employeesreport'; //员工财务列表
export const GET_OUTSTANDINGBILLS = 'get_outstandingbills'; //员工未结账单
export const GET_OUTSTANDINGBILLDETAIL = 'GET_OUTSTANDINGBILLDETAIL'; //员工未结账单明细
export const GET_RESTAURANTBILL = 'get_restaurantbill'; //餐厅未结账单
export const GET_HIGHESTSISHESSALES = 'get_highestsishessales'; //最高菜品销售
export const GET_HIGHESTDRINKSSALES = 'get_highestdrinkssales'; //最高酒水销售
export const GET_BEVERAGEANALYSIS = 'get_beverageanalysis'; //酒水分析报表
export const GET_OC = 'get_oc'; //oc报表
export const GET_FINANCIALMEALPERIOD = 'get_financialmealperiod'; //获取餐厅餐段报表的餐段
export const GET_SEGMENTREPORT = 'get_segmentreport'; //获取餐厅餐段报表的数据
export const GET_EMPLOYEEFINANCIALSTATEMENTS = 'get_employeefinancialstatements'; //员工财务报表
export const GET_SEGMENTSUMMARYREPORT = 'get_segmentsummaryreport'; //餐段概要报表
export const GET_RESTAURANTRETURNFOOD = 'get_restaurantreturnfood'; //餐厅退菜报表
export const GET_DISHESBIGTYPESALES = 'get_dishesbigtypesales'; //菜品销售大类报表
export const GET_DISHESSMALLTYPESALES = 'get_dishessmalltypesales'; //菜品销售小类报表
export const GET_TIPREPORT = 'get_tipreport'; //餐厅小费报表
export const GET_EMPLOYEESFOODBACK = 'get_employeesfoodback'; //餐厅退菜报表
export const GET_GETTABLEPEOPLEREPORT = 'GET_GETTABLEPEOPLEREPORT'; //餐桌人数销售报表
export const GET_TRANSACTIONDETAILDETAILS = 'GET_TRANSACTIONDETAILDETAILS'; //账单明细详情表
export const  GET_SELECTRESTURANTBILL = ' get_selectresturantbill'; //餐饮账单明细表
export const  GET_PMSLOG = ' get_pmslog'; //餐饮账单明细表
export const  GET_OPERATIONLOG = ' get_operationlog'; //后台操作日志
export const  GET_GETBREAKFASTLOG = ' get_getbreakfastlog'; //早餐消费日志报表
export const  GET_TABLECONSUMPTION = ' get_tableconsumption'; //餐桌消费报表
// export const SET_QUANTITY = 'SET_QUANTITY'; //传递变量


